/* RELATORIO GERAL DE TODOS OS CLIENTES (TELEFONE E ENDERECO) */
DESC CLIENTE;
DESC TELEFONE;
DESC ENDERECO;

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE  = E.ID_CLIENTE
ORDER BY C.IDCLIENTE;

/* RELATORIO DE HOMENS */
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE  = E.ID_CLIENTE
WHERE C.SEXO = 'M'
ORDER BY C.IDCLIENTE;

-- EXERCÍCIO ADICIONAL - CONSERTANDO SEXO DOS CLIENTES
SELECT IDCLIENTE, NOME, SEXO
FROM CLIENTE
WHERE IDCLIENTE = 12
OR IDCLIENTE = 13
OR IDCLIENTE = 18
OR IDCLIENTE = 19;

SELECT IDCLIENTE, NOME, SEXO
FROM CLIENTE
WHERE IDCLIENTE IN (12, 13, 18, 19);

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE IN (12, 13, 18, 19);

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 14;

/* RELATORIO DE MULHERES */
SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, T.TIPO, T.NUMERO, E.RUA, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE  = E.ID_CLIENTE
WHERE C.SEXO = 'F'
ORDER BY C.IDCLIENTE;

-- EXERCÍCIO ADICIONAL - CONSERTANDO SEXO DOS CLIENTES
SELECT IDCLIENTE, NOME, SEXO
FROM CLIENTE
WHERE IDCLIENTE = 16;

UPDATE CLIENTE
SET SEXO = 'M'
WHERE IDCLIENTE = 16;

/* QUANTIDADE DE HOMENS E MULHERES */
SELECT SEXO, COUNT(*) AS QUANTIDADE FROM CLIENTE GROUP BY SEXO;

/* IDS E EMAIL DAS MULHERES QUE MOREM NO CENTRO DO RIO DE JANEIRO E 
NAO TENHAM CELULAR */
SELECT C.IDCLIENTE, C.NOME, C.EMAIL, T.NUMERO, T.TIPO, E.BAIRRO, E.CIDADE, E.ESTADO
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
WHERE C.SEXO = 'F'
AND T.TIPO != 'CEL'
AND E.BAIRRO = 'CENTRO'
AND E.CIDADE = 'RIO DE JANEIRO';

-- RESOLUÇÃO FUTURA
SELECT C.IDCLIENTE, C.NOME, C.EMAIL
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
WHERE C.SEXO = 'F'
AND T.TIPO != 'CEL'
AND E.BAIRRO = 'CENTRO'
AND E.CIDADE = 'RIO DE JANEIRO'
GROUP BY C.IDCLIENTE;


/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */
SELECT C.NOME, C.EMAIL, T.NUMERO
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
WHERE T.TIPO = 'CEL'
AND E.ESTADO= 'RJ';


/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */
SELECT C.NOME, C.EMAIL, T.NUMERO AS CELULAR
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
WHERE C.SEXO = 'F'
AND E.ESTADO= 'SP';