USE DATABASE EMPRESA
GO

CREATE TABLE TB_EMPRESA (
    ID INT,
    NOME VARCHAR(50)
)
GO

CREATE TABLE ALUNO (
    IDALUNO INT PRIMARY KEY IDENTITY,
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(30) UNIQUE
)
GO

/* ADDING CONSTRAINTS */
ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO CHECK(SEXO IN('M', 'F'))
GO

/* 1X1 RELATION */
CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY IDENTITY(100, 10),
    BAIRRO VARCHAR(30),
    UF CHAR(2) NOT NULL
    CHECK (UF IN('RJ', 'SP', 'MG')),
    ID_ALUNO INT UNIQUE
)
GO

/* ADDING FK CONSTRAINT */
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES ALUNO(IDALUNO)
GO
