/* BRINGS ONLY THE ALUNOS THAT HAVE A NUMBER */
SELECT NOME, TIPO, NUMERO
FROM ALUNO INNER JOIN TELEFONE
ON IDALUNO = ID_ALUNO
GO

/* BRINGS ALL ALUNOS */
SELECT NOME, TIPO, NUMERO
FROM ALUNO LEFT JOIN TELEFONE
ON IDALUNO = ID_ALUNO
GO

/* DEALING WITH MORE ALIASES AND NULLS */
SELECT  A.NOME,
        ISNULL(T.TIPO, 'SEM NÚMERO') AS 'TIPO DE TELEFONE',
        ISNULL(T.NUMERO, 'SEM NÚMERO') AS 'TELEFONE',
        E.BAIRRO,
        E.UF
FROM ALUNO A LEFT JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO
INNER JOIN ENDERECO E
ON A.IDALUNO = E.ID_ALUNO
GO