/* GETTING THE CURRENT DATE */
SELECT GETDATE()

/* DATEDIFF - CALCULATES THE DIFFERENCE BETWEEN TWO DATES (RETURNS AN INT) */
SELECT NOME, DATEDIFF(DAY, NASCIMENTO, GETDATE()) AS "IDADE EM DIAS" FROM ALUNO
GO

SELECT NOME, DATEDIFF(MONTH, NASCIMENTO, GETDATE()) AS "IDADE EM DIAS" FROM ALUNO
GO

SELECT NOME, DATEDIFF(YEAR, NASCIMENTO, GETDATE()) AS "IDADE EM DIAS" FROM ALUNO
GO

/* MAKING MATH OPERATIONS WITH DATES */
SELECT DATEADD(YEAR, 10, GETDATE())
GO

/* DATENAME - GETTING THE SPECIFIED DATA IN A DATE (RETURNS VARCHAR) */
SELECT NOME, DATENAME(MONTH, NASCIMENTO) FROM ALUNO
GO

SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO) FROM ALUNO
GO

SELECT NOME, DATENAME(WEEK, NASCIMENTO) FROM ALUNO
GO

/* DATEPART - GETTING THE SPECIFIED DATA IN A DATE (RETURNS INT) */

SELECT NOME, DATEPART(DAY, NASCIMENTO) FROM ALUNO
GO

SELECT NOME, DATEPART(MONTH, NASCIMENTO) FROM ALUNO
GO

SELECT NOME, DATEPART(DAYOFYEAR, NASCIMENTO) FROM ALUNO
GO

SELECT NOME, DATEPART(QUARTER, NASCIMENTO) FROM ALUNO
GO

