SELECT NOME, CHARINDEX('A', NOME) AS INDICE FROM ALUNO
GO

SELECT NOME, CHARINDEX('A', NOME, 2) AS INDICE FROM ALUNO
GO

/* CREATING TABLE TO MAKE INSERT BULKING */
CREATE TABLE LANCAMENTO_CONTABIL(
    CONTA INT,
    VALOR INT,
    DEB_CRED CHAR(1)
)
GO

/* BULK INSERT - INSERTING DATA FROM A TXT FILE */
BULK INSERT LANCAMENTO_CONTABIL
FROM 'C:\Users\nostr\Desktop\CONTAS.txt'
WITH
(
    FIRSTROW = 2,
    DATAFILeTYPE = 'char',
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '\n'
)
GO