/* FINDING THE CURRENT CREDIT IN THE ACCOUNTS */
SELECT CONTA, SUM(VALOR)
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
GO

SELECT
	CONTA,
	CHARINDEX('C', DEB_CRED) AS CREDITO,
	CHARINDEX('D', DEB_CRED) AS DEBITO,
	CHARINDEX('C', DEB_CRED) * 2 - 1 AS MULTIPLICADOR
FROM LANCAMENTO_CONTABIL
GO

SELECT
	CONTA,
	SUM(VALOR * (CHARINDEX('C', DEB_CRED) * 2 - 1)) AS SALDO
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
GO