/* JOIN USING WHERE - NOT RECOMMENDED */
SELECT IDCLIENTE, NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE, TELEFONE
WHERE IDCLIENTE = ID_CLIENTE;

/* JOIN USING PROPER TAGS */
SELECT IDCLIENTE, NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;

/* QUERY USING PROJECTION (SELECT), JOIN AND SELECTION (WHERE) */
SELECT IDCLIENTE, NOME, SEXO, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F';


/* QUERY WITH MORE THAN TWO TABLES USING TABLES ALIAS */
-- NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE;
