/* Creating a new table */
CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT,
    FRETE FLOAT(10, 2) NOT NULL
);

/* Modifying an existing column */
ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

/* Another way to modify an existing column */
ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/* Adding a new column */
ALTER TABLE PRODUTO
ADD PESO FLOAT(10, 2) NOT NULL;

/* Adding a new column at a specific order in the table - MySQL only */
ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
ADD PESO FLOAT(10,2) NOT NULL
FIRST;

/* Deleting a column */
ALTER TABLE PRODUTO
DROP COLUMN PESO;