SELECT C.NOME, 
       C.SEXO,
       C.EMAIL,
       T.TIPO,
       T.NUMERO,
       E.BAIRRO,
       E.CIDADE,
       E.ESTADO
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE;

/* CREATING A VIEW */
CREATE VIEW V_RELATORIO AS
SELECT C.NOME, 
       C.SEXO,
       IFNULL(C.EMAIL, "CLIENTE SEM EMAIL") AS "E-MAIL",
       T.TIPO,
       T.NUMERO,
       E.BAIRRO,
       E.CIDADE,
       E.ESTADO
FROM CLIENTE C
    INNER JOIN TELEFONE T
    ON C.IDCLIENTE = T.ID_CLIENTE
    INNER JOIN ENDERECO E
    ON C.IDCLIENTE = E.ID_CLIENTE;

/* SEEING THE VIEW */
SELECT * FROM V_RELATORIO;

/* DELETING A VIEW */
DROP VIEW V_RELATORIO;

/* SELECTING EXPECIFIC COLUMNS IN A VIEW */
SELECT NOME, NUMERO, ESTADO FROM V_RELATORIO;