/* CREATING DB */
CREATE DATABASE OFICINA;

USE OFICINA;

CREATE TABLE CLIENTE(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO ENUM('M', 'F') NOT NULL,
    ID_CARRO_FK INT UNIQUE
);

-- ID_CARRO_FK AS UNIQUE SET THE RELATIONSHIP TO 1X1 WITH CARRO

CREATE TABLE TELEFONE(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CEL', 'RES', 'COM'),
    NUMERO VARCHAR(30) NOT NULL,
    ID_CLIENTE_FK INT
);

-- ID_CLIENTE_FK AS NOT UNIQUE AND NOT NULL SET THE RELATIONSHIP TO 1XN WITH CLIENTE

CREATE TABLE MARCA(
    ID_MARCA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE CARRO(
    ID_CARRO INT PRIMARY KEY AUTO_INCREMENT,
    CHASSI VARCHAR(30) NOT NULL UNIQUE,
    MODELO VARCHAR(30),
    ID_MARCA_FK INT UNIQUE
);

CREATE TABLE COR(
    ID_COR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE CARRO_COR(
    ID_CARRO_FK INT NOT NULL,
    ID_COR_FK INT NOT NULL,
    PRIMARY KEY(ID_CARRO_FK, ID_COR_FK)
);

/* ADDING CONSTRAINTS */
ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE_FK)
REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO_FK)
REFERENCES CARRO(ID_CARRO);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA_FK)
REFERENCES MARCA(ID_MARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR_FK)
REFERENCES COR(ID_COR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO_FK)
REFERENCES CARRO(ID_CARRO);

/* INSERTS */
INSERT INTO MARCA VALUES(NULL, "VOLKSWAGEN");
INSERT INTO MARCA VALUES(NULL, "HONDA");
INSERT INTO MARCA VALUES(NULL, "TOYOTA");
INSERT INTO MARCA VALUES(NULL, "FORD");
INSERT INTO MARCA VALUES(NULL, "NISSAN");
INSERT INTO MARCA VALUES(NULL, "LEXUS");
INSERT INTO MARCA VALUES(NULL, "CHEVROLET");
INSERT INTO MARCA VALUES(NULL, "FIAT");
INSERT INTO MARCA VALUES(NULL, "RENAULT");
INSERT INTO MARCA VALUES(NULL, "KIA");

INSERT INTO COR VALUES(NULL, "BRANCO");
INSERT INTO COR VALUES(NULL, "PRETO");
INSERT INTO COR VALUES(NULL, "AZUL-ESCURO");
INSERT INTO COR VALUES(NULL, "CINZA");
INSERT INTO COR VALUES(NULL, "VERMELHO");
INSERT INTO COR VALUES(NULL, "VERDE-ESCURO");
INSERT INTO COR VALUES(NULL, "PRETO-FOSCO");
INSERT INTO COR VALUES(NULL, "AMARELO");
INSERT INTO COR VALUES(NULL, "ROXO");
INSERT INTO COR VALUES(NULL, "VERDE");

INSERT INTO CARRO VALUES(NULL, "SD616887A2", "IS 500", 6);
INSERT INTO CARRO VALUES(NULL, "NGF5254545", "HILUX", 3);
INSERT INTO CARRO VALUES(NULL, "OUQWN54545", "GT-R", 5);
INSERT INTO CARRO VALUES(NULL, "12GSGSDGB3", "PALIO", 8);
INSERT INTO CARRO VALUES(NULL, "HF414SAF64", "POLO", 1);
INSERT INTO CARRO VALUES(NULL, "OTEA403453", "CAMARO", 7);
INSERT INTO CARRO VALUES(NULL, "NERTQA5325", "CIVIC", 2);
INSERT INTO CARRO VALUES(NULL, "ET003451DG", "MUSTANG", 4);
INSERT INTO CARRO VALUES(NULL, "3250235GSD", "KIWID", 9);
INSERT INTO CARRO VALUES(NULL, "LMWRQ04341", "SPORTAGE", 10);

INSERT INTO CLIENTE VALUES(NULL, "PEDRO", "M", 1);
INSERT INTO CLIENTE VALUES(NULL, "CARLA", "F", 2);
INSERT INTO CLIENTE VALUES(NULL, "JOÃO", "M", 3);
INSERT INTO CLIENTE VALUES(NULL, "ALEX", "M", 4);
INSERT INTO CLIENTE VALUES(NULL, "RENA", "F", 5);
INSERT INTO CLIENTE VALUES(NULL, "CARLOS", "M", 6);
INSERT INTO CLIENTE VALUES(NULL, "ELVIS", "M", 7);
INSERT INTO CLIENTE VALUES(NULL, "KIRA", "F", 8);
INSERT INTO CLIENTE VALUES(NULL, "FERNANDA", "F", 9);
INSERT INTO CLIENTE VALUES(NULL, "ELIAS", "M", 10);

CREATE TABLE TELEFONE(
    ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM('CEL', 'RES', 'COM'),
    NUMERO VARCHAR(30) NOT NULL,
    ID_CLIENTE_FK INT
);

INSERT INTO TELEFONE VALUES(NULL, "CEL", "(11)98144-5876", 1);
INSERT INTO TELEFONE VALUES(NULL, "COM", "(23)1409-464", 1);
INSERT INTO TELEFONE VALUES(NULL, "RES", "(63)6779-1150", 3);
INSERT INTO TELEFONE VALUES(NULL, "COM", "(11)2114-3654",4);
INSERT INTO TELEFONE VALUES(NULL, "CEL", "(61)92364-7234", 5);
INSERT INTO TELEFONE VALUES(NULL, "RES", "(77)5321-7879", 5);
INSERT INTO TELEFONE VALUES(NULL, "RES", "(79)5487-5643", 6);
INSERT INTO TELEFONE VALUES(NULL, "RES", "(11)5489-2125", 7);
INSERT INTO TELEFONE VALUES(NULL, "CEL", "(71)97341-5123", 8);
INSERT INTO TELEFONE VALUES(NULL, "RES", "(47)6436-5648", 8);
INSERT INTO TELEFONE VALUES(NULL, "COM", "(12)8725-3481", 9);
INSERT INTO TELEFONE VALUES(NULL, "CEL", "(75)97313-3643", 9);
INSERT INTO TELEFONE VALUES(NULL, "COM", "(77)7851-1366", 9);
INSERT INTO TELEFONE VALUES(NULL, "RES", "(23)6464-3215", 10);

INSERT INTO CARRO_COR VALUES(1,1);
INSERT INTO CARRO_COR VALUES(2,2);
INSERT INTO CARRO_COR VALUES(3,3);
INSERT INTO CARRO_COR VALUES(4,3);
INSERT INTO CARRO_COR VALUES(4,4);
INSERT INTO CARRO_COR VALUES(5,5);
INSERT INTO CARRO_COR VALUES(6,6);
INSERT INTO CARRO_COR VALUES(7,7);
INSERT INTO CARRO_COR VALUES(8,8);
INSERT INTO CARRO_COR VALUES(9,8);
INSERT INTO CARRO_COR VALUES(10,9);
INSERT INTO CARRO_COR VALUES(10,10);