USE my_first_db;

SELECT * FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIA@HOTMAIL.COM';

UPDATE CLIENTE
SET EMAIL = 'JOAO@IG.COM'
WHERE NOME = 'JOAO';

UPDATE CLIENTE
SET EMAIL = 'JORGE@IG.COM'
WHERE NOME = 'JORGE';

UPDATE CLIENTE
SET EMAIL = 'CELIA@HOTMAIL.COM'
WHERE NOME = 'CELIA';

UPDATE CLIENTE
SET EMAIL = 'ANA@GMAIL.COM'
WHERE NOME = 'ANA';

UPDATE CLIENTE
SET EMAIL = 'CARLA@HOTMAIL.COM'
WHERE NOME = 'CARLA';