CREATE TABLE TABELA(
    COLUNA1 VARCHAR(30),
    COLUNA2 VARCHAR(30),
    COLUNA3 VARCHAR(30)
);

/* ADDING A PRIMARY KEY TO AN EXISTING TABLE */
ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

/* VERIFYING THE TABLE */
DESC TABELA;

/* ADDING A NEW COLUMN */
ALTER TABLE TABELA
ADD COLUNA VARCHAR(30);

ALTER TABLE TABELA
ADD COLUNA100 INT;

/* ADDING COLUMN AT A SPECIFIC POSITION */
ALTER TABLE TABELA
ADD COLUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA3;

/* MODIFYING THE DATA TYPE OF A COLUMN */
ALTER TABLE TABELA
MODIFY COLUNA2 DATE NOT NULL;

/* RENAMING THE NAME OF THE TABLE */
ALTER TABLE TABELA
RENAME PESSOA;
 
DESC PESSOA;

/* CREATING A NEW TABLE */
CREATE TABLE TIME(
    IDTIME INT PRIMARY KEY AUTO_INCREMENT,
    TIME VARCHAR(30),
    ID_PESSOA VARCHAR(30)
);

/* ADDING A FOREIGN KEY FOREIGN KEY */
ALTER TABLE TIME
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/* SHOWING MORE DETAILED INFORMATION ABOUT THE TABLE */
SHOW CREATE TABLE TIME;