CREATE DATABASE DB_FOR_TRIGGERS;

USE DB_FOR_TRIGGERS;

CREATE TABLE USER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE BACKUP_USER(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL UNIQUE
);

/* CREATING TRIGGERS */
DELIMITER $
CREATE TRIGGER SAVE_DELETED_USER
BEFORE DELETE ON USER
FOR EACH ROW
BEGIN
    INSERT INTO BACKUP_USER VALUES(NULL, OLD.ID, OLD.NOME, OLD.USERNAME);
END
$
DELIMITER ;

/* INSERTS FOR THE TABLE */
INSERT INTO USER VALUES(NULL, "ODA ERI", "ODA225", "8u38r0912k412215112414129412498");
INSERT INTO USER VALUES(NULL, "KIRA MASUMOTO", "KIRACHAN", "f1q5w146rqw6r1sa2f135834");
INSERT INTO USER VALUES(NULL, "YUI TAKEMOTO", "TAKE", "320masm093u91ujmksnbjb8230");
INSERT INTO USER VALUES(NULL, "TEN YAMASAKI", "TENCHAN", "41352131jm10-kr12kr-1rmjfn");

DELETE FROM USER WHERE ID = 3;